6-4-pageview
Sotonka/places pull request #22
Opened 2023-01-20 02:43 UTC by Sotonka

![1](https://user-images.githubusercontent.com/71734734/213606782-10daaece-8934-4abc-9bc8-e6609a9960b3.png)

2023-01-20 02:47 UTC, Sotonka commented
на картинке третий слайд темной темы не тот вставил

2023-01-20 13:05 UTC, GeorgeOblomov commented on lib/ui/screen/onboarding_screen.dart
> +                if (provider.page == 2)
Не очень красиво по-моему. Думаю лучше в случае последнего слайда ничего не возвращать или SizedBox.shrink()

2023-01-20 13:09 UTC, egrischenkov commented on lib/ui/screen/onboarding_screen.dart
> +        if (page == 0) const _ActiveDot() else const _Dot(),
Думаю не очень гибкое решение, с той точки зрения если предположить, что дизайнеры попросят позже добавить еще 5 страниц онбординга. Тогда придется ручками править этот виджет добавляя еще пять условий. Лучше отталкиваться от количества страниц и например перебрать количество циклом for и проверить на isSelected

2023-01-20 13:13 UTC, GeorgeOblomov commented on lib/ui/screen/sight_details.dart
> +              }(),
Какие-то странные скобочки.

2023-01-20 13:14 UTC, GeorgeOblomov requested changes
Давайте поправим, то о чем я отписал, если не против. Как справитесь, можете мне отписать в телегам, чтобы я проверил и не блочить вас на выходных.

2023-01-22 22:07 UTC, Sotonka commented on lib/ui/screen/onboarding_screen.dart
> +                if (provider.page == 2)
исправил

2023-01-22 22:25 UTC, Sotonka commented on lib/ui/screen/onboarding_screen.dart
> +        if (page == 0) const _ActiveDot() else const _Dot(),
исправил

2023-01-22 22:27 UTC, Sotonka commented on lib/ui/screen/onboarding_screen.dart
> +                if (provider.page == 2)
некрасиво, но по другому не придумал
смысл в том что в appbar`е должен быть виджет по ширине текста, иначе контент съезжает

2023-01-22 22:30 UTC, Sotonka commented on lib/ui/screen/sight_details.dart
> +              }(),
нагуглил вот так:
https://stackoverflow.com/questions/49713189/how-to-use-conditional-statement-within-child-attribute-of-a-flutter-widget-cen

без них не работает, а конструкция <условие>? : не подходит

2023-01-22 22:33 UTC, Sotonka commented on lib/ui/screen/sight_details.dart
> +              }(),
исправил

2023-01-23 16:51 UTC, GeorgeOblomov commented on lib/ui/screen/onboarding_screen.dart
> +                if (provider.page == 2)
Хмм. Ну да действительно. Тогда можно было бы указать высоту этому виджету. Либо явно, либо через constraints

2023-01-23 16:51 UTC, GeorgeOblomov approved these changes

2023-01-23 22:19 UTC, merged